### ISSUE TITLE
Use `remote-info` instead of `remote-ls`?

### ISSUE THREAD

**Issue by xrat** [ivanalejandro0/flatpak-update-checker#1] opened 2023-11-13 23:52 UTC
Disclaimer: I am newbie regarding flatpak.

My flatpaks don't (always?) show the new version when I run `remote-ls`, but `remote-info` apparently does:

```
$ python flatpak-check-updates.py 
net.mkiol.SpeechNote: 4.2.1 -> 4.2.1 [rebuild]

$ flatpak remote-ls --all --updates
Name              Application ID             Version      Branch      Arch
Speech Note       net.mkiol.SpeechNote       4.2.1        stable      x86_64

$ flatpak remote-info flathub net.mkiol.SpeechNote | grep -E '(ID|Subject): '
        ID: net.mkiol.SpeechNote
   Subject: Release 4.3.0 (#37) (f137f97f)
```

**Comment by ivanalejandro0** [comment] 2023-11-15 19:26
Oh, no worries, I'm no expert either.
Thanks for the report, I was able to reproduce it.

```
$ ./flatpak-check-updates.py
org.gimp.GIMP: 2.10.34 -> 2.10.34 [rebuild]

$ flatpak remote-ls --all --updates
Name                                           Application ID                     Version          Branch         Arch
GNU Image Manipulation Program                 org.gimp.GIMP                      2.10.34          stable         x86_64

$ flatpak remote-info flathub org.gimp.GIMP | grep -E '(ID|Subject): '
        ID: org.gimp.GIMP
   Subject: Removing the branch metadata. (3cd49e36)
```

But from what I see, the `Subject` line cannot be trusted to contain the version since as you see for the GIMP case, there's no version there, and there is a new 2.10.36 version on https://flathub.org/apps/org.gimp.GIMP
I also checked all the info that `remote-info` provides and there's no version in there either.

I found a fix for this,

```
$ flatpak update --appstream

$ ./flatpak-check-updates.py
org.gimp.GIMP: 2.10.34 -> 2.10.36 [update]
```

For some reason it seems that using `remote-ls` is not enough. I'll add that line to the script to fix the issue.

**Comment by ivanalejandro0** [comment] 2023-11-15 19:29
I just pushed a fix for this on https://github.com/ivanalejandro0/flatpak-update-checker/commit/a40a7275c36fc2a649738d33897c5d339f787224
@xrat , would you mind checking out if that works for you?

**Comment by xrat** [comment] 2023-11-16 18:34
Great, finally I learned what `--appstream` was for ;-)

I don't have many flatpaks to test this on right now but it did work just fine today here:

```
$ flatpak remote-ls --all --updates 
Name                    Application ID                  Version          Branch   Arch
Chromium Web Browser    org.chromium.Chromium           119.0.6045.123   stable   x86_64
Codecs                  org.chromium.Chromium.Codecs                     stable   x86_64
$ python flatpak-check-updates.py   ## old version
org.chromium.Chromium: 119.0.6045.123 -> 119.0.6045.123 [rebuild]
org.chromium.Chromium.Codecs: [unknown]
$ mv flatpak-check-updates.py{,.bak}
$ wget -q https://github.com/ivanalejandro0/flatpak-update-checker/raw/main/flatpak-check-updates.py
$ python flatpak-check-updates.py 
org.chromium.Chromium: 119.0.6045.123 -> 119.0.6045.159 [update]
org.chromium.Chromium.Codecs: [unknown]
$ flatpak remote-ls --all --updates
Name                    Application ID                  Version          Branch   Arch
Chromium Web Browser    org.chromium.Chromium           119.0.6045.159   stable   x86_64
Codecs                  org.chromium.Chromium.Codecs                     stable   x86_64
```

**Comment by ivanalejandro0** [comment] 2023-11-18 20:07
The documentation for `--appstream` wasn't helpful for me at all, It was trial and error for me to figure it out.

I'm closing this issue then, thanks for reporting and the feedback!

**Closed as completed** 2023-11-18 20:07 UTC
